// Generated by scripts/og/install.mjs from scripts/og/function-template.js — do not edit by hand
// (scripts/og/audit.mjs compares this file byte-for-byte across all 28 sites).
//
// Serves the seasonal share card at /og.jpg: og-summer.jpg May–Sep, og-winter.jpg Oct–Apr — the same
// rule the site's own runtime seasonal() uses to pick the home hero, so the WhatsApp / Facebook /
// LinkedIn preview shows the picture the visitor actually lands on. No rebuild at the turn of the season.
//
// 🔴 The route is /og.jpg and NOT /og-default.jpg on purpose: a Pages Function whose path collides with a
// static asset of the same name has ambiguous precedence, so the two never share a name. Legacy shares
// scraped before 2026-09-06 still point at the static /og-default.jpg, which stays in place.
//
// Any failure falls through to that static file, so the worst case is the previous behaviour, never a 500.
export async function onRequest({ request, env }) {
  const url = new URL(request.url);
  const month = new Date().getUTCMonth() + 1;
  const season = month >= 5 && month <= 9 ? 'summer' : 'winter';
  for (const name of [`/og-${season}.jpg`, '/og-default.jpg']) {
    try {
      const res = await env.ASSETS.fetch(new Request(url.origin + name, { method: 'GET' }));
      if (!res.ok) continue;
      const headers = new Headers(res.headers);
      headers.set('Content-Type', 'image/jpeg');
      headers.set('Cache-Control', 'public, max-age=86400');
      headers.set('X-LV-OG-Season', name === '/og-default.jpg' ? 'fallback' : season);
      return new Response(res.body, { status: 200, headers });
    } catch (_) { /* try the next candidate */ }
  }
  return new Response('Share card not found', { status: 404 });
}
