/**
 * Appimainoksen tekstit 12 kielellä — shared/appPromo/. Kanoninen lv-opsissa; sivustoilla vendoroitu kopio
 * src/shared/appPromo/copy.ts (gate:apppromo-kopiot vertaa tavuilleen; laplandstaysillä zh-CN muunnettu zh-hant.mjs:llä).
 *
 * MISTÄ TEKSTIT TULEVAT (1.10.2026):
 *  - screens[<näkymä>][0] = appin oma välilehden nimi (zh events = appin 节庆赛事 2.10.2026, ennen 活动 kahdesti) (appin käännöstiedostot: surface.near, surface.view.weather,
 *    nav.taxi, nav.snowmobileRoutes, nav.outdoors, nav.activities, nav.events, outdoors.modes.ski, carHelp.title), jotta
 *    lukija tunnistaa sen appissa. Rivit [1] appin nav.sub-tekstistä, paitsi now, sos, routes, ski, carhelp, activities.
 *  - note + lead = appin oma asennuslause (install.installingIsFreeAnd) kahtia jaettuna: "ilmainen, ei kauppatiliä" ja
 *    "toimii ilman verkkoa: paikat, reitit ja hätänumerot ovat tallessa puhelimessa". Lupaus on appin, ei mainoksen.
 *  - cta, scan, dismiss = 28 sivustokopion käännöskorjaukset koottuna (it Lei-muodot, es teléfono, nl Download …).
 *  - title = aiheen otsikko, lukijan tilanne tällä sivustolla (CLAUDE.md "Mainos rakennetaan sivun aiheesta käsin").
 *  - UNIT_COPY = laplandvisitin revontuli- (8.9.) ja hätänumeroyksiköt (9.9.) sellaisinaan.
 *
 * "Everything Lapland." EI ole tässä: brändiohjeen §1 mukaan se kulkee logon mukana englanniksi kaikilla kielillä
 * (komponentin Lockup), ja otsikko on kokonaan sivun kielellä (Vesa 1.10.2026).
 *
 * 🔴 CJK-otsikoissa ja -otsakkeissa | = fraasiraja: komponentti tekee siitä <wbr>-katkokohdan ja asettaa keep-all, jotta
 * otsikko ei katkea kesken sanan (cjk_otsikot_rivitys_20260927). Merkki ei näy tekstissä eikä textContentissa.
 * 🔴 ski-rivin {slopes} {lifts} {resorts} täyttyvät appStats.ts:stä (laskettu appin datasta), eivät käännöksestä.
 */
import type { Screen } from './screens';

export type TextFocus = 'general' | 'snowmobile' | 'ski' | 'stay' | 'move' | 'outdoors' | 'do' | 'eat';
export type Copy = {
  cta: string;
  /** Napin alle: asennus on ilmainen, ei kauppatiliä. */
  note: string;
  /** Otsikon alle: mitä asennettu appi tekee ilman verkkoa. */
  lead: string;
  scan: string;
  dismiss: string;
  /** Kuvan alt-etuliite: "<alt>: <näkymän nimi>". */
  alt: string;
  title: Record<TextFocus, string>;
  /** [otsake = appin välilehden nimi, rivi = mitä siellä on] */
  screens: Record<Exclude<Screen, 'aurora'>, readonly [string, string]>;
};
export type UnitCopy = { title: string; lead: string; features: readonly [string, string, string]; note: string };

export const COPY: Record<string, Copy> = {
  en: {
    cta: 'Get the free app',
    note: 'Installing is free and needs no store account.',
    lead: 'Once installed the app works offline too: places, trails and emergency numbers stay on the phone.',
    scan: 'Scan to open on your phone',
    dismiss: 'Close',
    alt: 'LaplandVibes app screen',
    title: {
      general: 'In Lapland? Keep the essentials in your pocket.',
      snowmobile: 'Snowmobiling in the fells? Take the routes with you.',
      ski: 'Skiing in Lapland? Resorts and weather in your pocket.',
      stay: 'Checked in? The area around you, in your pocket.',
      move: 'On the move in Lapland? Roads and help in your pocket.',
      outdoors: 'Heading outdoors? Take the trails with you.',
      do: 'What to do in Lapland? Tours and events in your pocket.',
      eat: 'Hungry on arrival? The nearest places in your pocket.',
    },
    screens: {
      now: ['Right now', 'Weather, aurora chance and wind at your destination'],
      near: ['Nearby', 'Restaurants, saunas, shops'],
      weather: ['Weather & roads', 'Hour by hour, official Finnish forecast'],
      sos: ['Emergency numbers', '112 and other helplines as call buttons'],
      routes: ['Snowmobile routes', 'Every marked trail, by municipality'],
      ski: ['Ski resorts', '{slopes} slopes and {lifts} lifts at {resorts} resorts'],
      taxi: ['Taxi', 'Local numbers, per destination'],
      carhelp: ['Car help', 'Towing, tyres and repairs, nearest first'],
      outdoors: ['Outdoors', 'Trails, camping, lean-tos'],
      activities: ['Activities', 'Trips you can book at your destination'],
      events: ['Events', 'Festivals and races'],
    },
  },
  fi: {
    cta: 'Lataa ilmainen sovellus',
    note: 'Asennus on ilmainen eikä vaadi kauppatiliä.',
    lead: 'Asennettuna appi toimii myös ilman verkkoa: paikat, reitit ja hätänumerot ovat tallessa puhelimessa.',
    scan: 'Skannaa ja avaa puhelimessa',
    dismiss: 'Sulje',
    alt: 'LaplandVibes-sovelluksen näkymä',
    title: {
      general: 'Perillä Lapissa? Kaikki tarpeellinen taskussa.',
      snowmobile: 'Kelkalla tunturiin? Ota reitit mukaan.',
      ski: 'Laskemaan Lappiin? Rinteet ja sää taskussa.',
      stay: 'Perillä majapaikassa? Lähiseutu taskussa.',
      move: 'Liikkeellä Lapissa? Keli ja apu taskussa.',
      outdoors: 'Retkelle luontoon? Ota reitit mukaan.',
      do: 'Tekemistä Lapissa? Retket ja tapahtumat taskussa.',
      eat: 'Nälkä perillä? Lähimmät ravintolat taskussa.',
    },
    screens: {
      now: ['Nyt kohteessa', 'Sää, revontulien todennäköisyys ja tuuli'],
      near: ['Lähellä', 'Ravintolat, saunat, kaupat'],
      weather: ['Sää ja keli', 'Tunneittain, Ilmatieteen laitos'],
      sos: ['Hätänumerot', '112 ja muut numerot soittonappeina'],
      routes: ['Kelkkareitit', 'Kaikki merkityt urat kunnittain'],
      ski: ['Hiihtokeskukset', '{slopes} rinnettä ja {lifts} hissiä, {resorts} keskusta'],
      taxi: ['Taksi', 'Paikalliset numerot kohteittain'],
      carhelp: ['Apua autolle', 'Hinaus, renkaat ja korjaamot, lähin ensin'],
      outdoors: ['Ulkoilu', 'Reitit, leirintä, laavut'],
      activities: ['Aktiviteetit', 'Varattavat retket kohteittain'],
      events: ['Tapahtumat', 'Festarit ja kisat'],
    },
  },
  sv: {
    cta: 'Hämta appen gratis',
    note: 'Installationen är gratis och kräver inget butikskonto.',
    lead: 'Installerad fungerar appen även utan nät: platser, leder och nödnummer finns i telefonen.',
    scan: 'Skanna för att öppna i telefonen',
    dismiss: 'Stäng',
    alt: 'Vy i LaplandVibes-appen',
    title: {
      general: 'Framme i Lappland? Det viktigaste i fickan.',
      snowmobile: 'Ut på fjället med skoter? Ta med lederna.',
      ski: 'Skidåkning i Lappland? Backar och väder i fickan.',
      stay: 'Framme vid boendet? Närområdet i fickan.',
      move: 'På vägarna i Lappland? Väglag och hjälp i fickan.',
      outdoors: 'Ut i naturen? Ta med lederna.',
      do: 'Vad gör man i Lappland? Turer och evenemang i fickan.',
      eat: 'Hungrig efter resan? Närmaste matställena i fickan.',
    },
    screens: {
      now: ['Just nu', 'Väder, norrskenschans och vind på resmålet'],
      near: ['Nära', 'Restauranger, bastur, butiker'],
      weather: ['Väder och väglag', 'Timme för timme, finska prognosen'],
      sos: ['Nödnummer', '112 och andra nummer som ringknappar'],
      routes: ['Skoterleder', 'Alla markerade leder, kommun för kommun'],
      ski: ['Skidorter', '{slopes} backar och {lifts} liftar i {resorts} skidorter'],
      taxi: ['Taxi', 'Lokala nummer per ort'],
      carhelp: ['Bilhjälp', 'Bärgning, däck och verkstäder, närmast först'],
      outdoors: ['Friluftsliv', 'Leder, camping, vindskydd'],
      activities: ['Aktiviteter', 'Turer att boka på resmålet'],
      events: ['Evenemang', 'Festivaler och tävlingar'],
    },
  },
  de: {
    cta: 'Kostenlose App holen',
    note: 'Die Installation ist kostenlos und braucht kein Store-Konto.',
    lead: 'Einmal installiert läuft die App auch offline: Orte, Routen und Notrufnummern bleiben auf dem Handy.',
    scan: 'Mit dem Handy scannen und öffnen',
    dismiss: 'Schließen',
    alt: 'Ansicht der LaplandVibes-App',
    title: {
      general: 'In Lappland angekommen? Das Wichtigste in der Tasche.',
      snowmobile: 'Mit dem Schneemobil ins Fjäll? Die Routen immer dabei.',
      ski: 'Skifahren in Lappland? Pisten und Wetter immer dabei.',
      stay: 'Angekommen? Die Umgebung in der Tasche.',
      move: 'Unterwegs in Lappland? Straßenzustand und Pannenhilfe.',
      outdoors: 'Raus in die Natur? Die Wanderwege immer dabei.',
      do: 'Was tun in Lappland? Touren und Events in der Tasche.',
      eat: 'Hungrig angekommen? Lokale in der Nähe.',
    },
    screens: {
      now: ['Jetzt vor Ort', 'Wetter, Polarlicht-Chance und Wind am Reiseziel'],
      near: ['In der Nähe', 'Restaurants, Saunen, Läden'],
      weather: ['Wetter & Straße', 'Stunde für Stunde, offizielle Vorhersage'],
      sos: ['Notrufnummern', '112 und weitere Nummern direkt anrufen'],
      routes: ['Schneemobil-Routen', 'Alle markierten Strecken, nach Gemeinden'],
      ski: ['Skigebiete', '{slopes} Pisten und {lifts} Lifte in {resorts} Skigebieten'],
      taxi: ['Taxi', 'Lokale Nummern je Ort'],
      carhelp: ['Auto-Hilfe', 'Abschleppdienst, Reifen und Werkstätten, nächstgelegene zuerst'],
      outdoors: ['Draußen', 'Wege, Camping, Schutzhütten'],
      activities: ['Aktivitäten', 'Buchbare Touren am Reiseziel'],
      events: ['Events', 'Festivals und Wettkämpfe'],
    },
  },
  fr: {
    cta: 'Obtenir l’appli gratuite',
    note: 'L\'installation est gratuite et ne demande aucun compte de store.',
    lead: 'Une fois installée, l\'application fonctionne aussi hors ligne : les lieux, les itinéraires et les numéros d\'urgence restent sur le téléphone.',
    scan: 'Scannez pour ouvrir sur votre téléphone',
    dismiss: 'Fermer',
    alt: 'Écran de l’appli LaplandVibes',
    title: {
      general: 'En Laponie ? L’essentiel dans votre poche.',
      snowmobile: 'En motoneige sur les fjälls ? Emportez les pistes.',
      ski: 'Du ski en Laponie ? Stations et météo dans votre poche.',
      stay: 'Sur place ? Les alentours dans votre poche.',
      move: 'Au volant en Laponie ? Routes et dépannage en poche.',
      outdoors: 'Envie de nature ? Emportez les sentiers.',
      do: 'Que faire en Laponie ? Sorties et événements en poche.',
      eat: 'Une petite faim ? Les adresses proches en poche.',
    },
    screens: {
      now: ['En ce moment', 'Météo, chances d’aurores et vent à destination'],
      near: ['À proximité', 'Restaurants, saunas, magasins'],
      weather: ['Météo et routes', 'Heure par heure, prévisions officielles'],
      sos: ['Numéros d’urgence', 'Le 112 et d’autres numéros à appeler en un geste'],
      routes: ['Pistes motoneige', 'Tous les itinéraires balisés, par commune'],
      ski: ['Stations de ski', '{slopes} pistes et {lifts} remontées dans {resorts} stations'],
      taxi: ['Taxi', 'Numéros locaux par destination'],
      carhelp: ['Assistance auto', 'Remorquage, pneus et garages, classés par distance'],
      outdoors: ['Plein air', 'Sentiers, camping, abris'],
      activities: ['Activités', 'Sorties à réserver à destination'],
      events: ['Événements', 'Festivals et compétitions'],
    },
  },
  es: {
    cta: 'Consiga la app gratis',
    note: 'Instalarla es gratis y no hace falta cuenta de ninguna tienda.',
    lead: 'Una vez instalada la app funciona también sin conexión: los sitios, las rutas y los números de emergencia se quedan en el móvil.',
    scan: 'Escanee para abrirla en su teléfono',
    dismiss: 'Cerrar',
    alt: 'Pantalla de la app LaplandVibes',
    title: {
      general: '¿Ya en Laponia? Lo esencial en su bolsillo.',
      snowmobile: '¿Sale en moto de nieve? Lleve las rutas consigo.',
      ski: '¿Esquí en Laponia? Pistas y clima en su bolsillo.',
      stay: '¿Ya en su alojamiento? Los alrededores en su bolsillo.',
      move: '¿Recorre Laponia? Carreteras y ayuda en su bolsillo.',
      outdoors: '¿Sale a la naturaleza? Lleve los senderos consigo.',
      do: '¿Qué hacer en Laponia? Excursiones y eventos a mano.',
      eat: '¿Llega con hambre? Restaurantes cercanos a mano.',
    },
    screens: {
      now: ['Ahora mismo', 'Clima, probabilidad de auroras y viento en su destino'],
      near: ['Cerca', 'Restaurantes, saunas, tiendas'],
      weather: ['Tiempo y carreteras', 'Hora a hora, previsión oficial'],
      sos: ['Números de emergencia', 'El 112 y otros números para llamar con un toque'],
      routes: ['Rutas en moto de nieve', 'Todas las rutas señalizadas, por municipio'],
      ski: ['Estaciones de esquí', '{slopes} pistas y {lifts} remontes en {resorts} estaciones'],
      taxi: ['Taxi', 'Números locales por destino'],
      carhelp: ['Ayuda en carretera', 'Grúa, neumáticos y talleres, por cercanía'],
      outdoors: ['Al aire libre', 'Rutas, camping, refugios'],
      activities: ['Actividades', 'Excursiones para reservar en su destino'],
      events: ['Eventos', 'Festivales y carreras'],
    },
  },
  it: {
    cta: 'Scarichi l’app gratis',
    note: 'L\'installazione è gratuita e non serve un account dello store.',
    lead: 'Una volta installata l\'app funziona anche offline: luoghi, itinerari e numeri di emergenza restano sul telefono.',
    scan: 'Inquadri il codice per aprirla sul telefono',
    dismiss: 'Chiuda',
    alt: 'Schermata dell’app LaplandVibes',
    title: {
      general: 'In Lapponia? L’essenziale in tasca.',
      snowmobile: 'In motoslitta sui monti? Porti con sé i percorsi.',
      ski: 'A sciare in Lapponia? Comprensori e meteo in tasca.',
      stay: 'Già sul posto? I dintorni in tasca.',
      move: 'In viaggio in Lapponia? Strade e assistenza in tasca.',
      outdoors: 'Voglia di natura? Porti con sé i sentieri.',
      do: 'Cosa fare in Lapponia? Escursioni ed eventi in tasca.',
      eat: 'Fame all’arrivo? I locali più vicini in tasca.',
    },
    screens: {
      now: ['Adesso', 'Meteo, probabilità di aurore e vento a destinazione'],
      near: ['Vicino', 'Ristoranti, saune, negozi'],
      weather: ['Meteo e strade', 'Ora per ora, previsioni ufficiali'],
      sos: ['Numeri di emergenza', 'Il 112 e altri numeri da chiamare con un tocco'],
      routes: ['Piste per motoslitta', 'Tutti i percorsi segnalati, per comune'],
      ski: ['Comprensori sciistici', '{slopes} piste e {lifts} impianti in {resorts} comprensori'],
      taxi: ['Taxi', 'Numeri locali per destinazione'],
      carhelp: ['Assistenza auto', 'Carro attrezzi, gomme e officine, dal più vicino'],
      outdoors: ['All\'aperto', 'Sentieri, campeggio, ripari'],
      activities: ['Attività', 'Escursioni da prenotare a destinazione'],
      events: ['Eventi', 'Festival e gare'],
    },
  },
  nl: {
    cta: 'Download de gratis app',
    note: 'Installeren is gratis en u hebt geen storeaccount nodig.',
    lead: 'Eenmaal geïnstalleerd werkt de app ook offline: plekken, routes en alarmnummers blijven op de telefoon staan.',
    scan: 'Scan om op uw telefoon te openen',
    dismiss: 'Sluiten',
    alt: 'Scherm van de LaplandVibes-app',
    title: {
      general: 'In Lapland aangekomen? Het belangrijkste op zak.',
      snowmobile: 'Met de sneeuwscooter het fjäll op? Neem de routes mee.',
      ski: 'Skiën in Lapland? Pistes en weerbericht op zak.',
      stay: 'Ingecheckt? De omgeving op zak.',
      move: 'Onderweg in Lapland? Wegdek en hulp op zak.',
      outdoors: 'De natuur in? Neem de routes mee.',
      do: 'Wat te doen in Lapland? Tochten en evenementen op zak.',
      eat: 'Trek bij aankomst? Restaurants in de buurt op zak.',
    },
    screens: {
      now: ['Nu ter plaatse', 'Weer, kans op noorderlicht en wind op uw bestemming'],
      near: ['Dichtbij', 'Restaurants, sauna\'s, winkels'],
      weather: ['Weer & wegdek', 'Uur voor uur, officiële verwachting'],
      sos: ['Alarmnummers', '112 en andere nummers als belknoppen'],
      routes: ['Sneeuwscooterroutes', 'Alle gemarkeerde routes, per gemeente'],
      ski: ['Skigebieden', '{slopes} pistes en {lifts} liften in {resorts} skigebieden'],
      taxi: ['Taxi', 'Lokale nummers per plaats'],
      carhelp: ['Autohulp', 'Sleepdienst, banden en garages, dichtstbijzijnde eerst'],
      outdoors: ['Buiten', 'Routes, camping, schuilhutten'],
      activities: ['Activiteiten', 'Tochten om te boeken op uw bestemming'],
      events: ['Evenementen', 'Festivals en wedstrijden'],
    },
  },
  'pt-BR': {
    cta: 'Baixar o app grátis',
    note: 'Instalar é gratuito e não precisa de conta em loja.',
    lead: 'Depois de instalado, o aplicativo funciona offline também: lugares, trilhas e telefones de emergência ficam no celular.',
    scan: 'Escaneie para abrir no celular',
    dismiss: 'Fechar',
    alt: 'Tela do app LaplandVibes',
    title: {
      general: 'Chegou à Lapônia? O essencial no seu bolso.',
      snowmobile: 'De motoneve pelas montanhas? Leve as rotas com você.',
      ski: 'Vai esquiar na Lapônia? Estações e clima no seu bolso.',
      stay: 'Já se instalou? Os arredores no seu bolso.',
      move: 'Rodando pela Lapônia? Estradas e ajuda no seu bolso.',
      outdoors: 'Rumo à natureza? Leve as trilhas com você.',
      do: 'O que fazer na Lapônia? Passeios e eventos no bolso.',
      eat: 'Chegou com fome? Restaurantes por perto no seu bolso.',
    },
    screens: {
      now: ['Agora', 'Clima, chance de aurora e vento no seu destino'],
      near: ['Por perto', 'Restaurantes, saunas, lojas'],
      weather: ['Clima e estradas', 'Hora a hora, previsão oficial'],
      sos: ['Números de emergência', 'O 112 e outros números para ligar com um toque'],
      routes: ['Rotas de motoneve', 'Todas as rotas sinalizadas, por município'],
      ski: ['Estações de esqui', '{slopes} pistas e {lifts} teleféricos em {resorts} estações'],
      taxi: ['Táxi', 'Números locais por destino'],
      carhelp: ['Ajuda no carro', 'Guincho, pneus e oficinas, por proximidade'],
      outdoors: ['Ao ar livre', 'Trilhas, camping, abrigos'],
      activities: ['Atividades', 'Passeios para reservar no seu destino'],
      events: ['Eventos', 'Festivais e competições'],
    },
  },
  ja: {
    cta: '無料アプリを入手',
    note: 'インストールは無料で、ストアのアカウントも不要です。',
    lead: '入れてしまえばオフラインでも使えます。スポット、ルート、緊急番号は端末に残ります。',
    scan: 'スキャンしてスマホで開く',
    dismiss: '閉じる',
    alt: 'LaplandVibesアプリの画面',
    title: {
      general: 'ラップランドに|着いたら、|必要な|情報は|スマホに。',
      snowmobile: 'スノーモービルで|山へ？|ルートは|スマホで|チェック。',
      ski: 'ラップランドで|スキー？|スキー場と|天気を|スマホで。',
      stay: '宿に|着いたら、|周辺の|情報は|スマホに。',
      move: 'ラップランドを|移動中？|路面状況と|車の|トラブル対応を|スマホで。',
      outdoors: '自然の|中へ？|トレイルは|スマホで|チェック。',
      do: 'ラップランドで|何しよう？|ツアーと|イベントを|スマホで。',
      eat: '着いたら|まずは|ごはん？|近くの|お店を|スマホで。',
    },
    screens: {
      now: ['現地の|今', '天気、オーロラ出現確率、風'],
      near: ['近く', 'レストラン・サウナ・店'],
      weather: ['天気と|路面', '1時間ごとの公式予報'],
      sos: ['緊急|番号', '112などの番号をワンタップで発信'],
      routes: ['スノーモービル|ルート', '標識のあるルートを自治体別に'],
      ski: ['スキー場', '{resorts}か所のスキー場、コース{slopes}本とリフト{lifts}基'],
      taxi: ['タクシー', '目的地ごとの地元の番号'],
      carhelp: ['車の|トラブル', 'レッカー、タイヤ、修理工場を近い順に'],
      outdoors: ['アウトドア', 'トレイル・キャンプ・シェルター'],
      activities: ['アクティビティ', '目的地で予約できるツアー'],
      events: ['イベント', 'フェスと大会'],
    },
  },
  ko: {
    cta: '무료 앱 받기',
    note: '설치는 무료이고 스토어 계정도 필요 없습니다.',
    lead: '설치하면 오프라인에서도 쓸 수 있습니다. 장소와 코스, 긴급 번호는 휴대폰에 남습니다.',
    scan: '스캔해서 휴대폰에서 열기',
    dismiss: '닫기',
    alt: 'LaplandVibes 앱 화면',
    title: {
      general: '라플란드에 도착하셨나요? 필요한 정보는 휴대폰에.',
      snowmobile: '스노모빌로 산에 가시나요? 루트를 챙겨 가세요.',
      ski: '라플란드에서 스키 타시나요? 스키장과 날씨를 휴대폰에.',
      stay: '숙소에 도착하셨나요? 주변 정보를 휴대폰에.',
      move: '라플란드에서 이동 중이신가요? 노면과 차량 도움을 휴대폰에.',
      outdoors: '자연으로 떠나시나요? 트레일을 챙겨 가세요.',
      do: '라플란드에서 무엇을 할까요? 투어와 행사를 휴대폰에.',
      eat: '도착해서 배가 고프세요? 가까운 식당을 휴대폰에.',
    },
    screens: {
      now: ['지금 현지', '날씨, 오로라 확률, 바람'],
      near: ['주변', '식당·사우나·상점'],
      weather: ['날씨와 노면', '시간별 공식 예보'],
      sos: ['긴급 전화번호', '112 등 주요 번호를 터치 한 번으로 연결'],
      routes: ['스노모빌 루트', '표시된 모든 루트를 지자체별로'],
      ski: ['스키장', '스키장 {resorts}곳, 슬로프 {slopes}개와 리프트 {lifts}개'],
      taxi: ['택시', '목적지별 현지 번호'],
      carhelp: ['차량 도움', '견인·타이어·정비소를 가까운 순으로'],
      outdoors: ['아웃도어', '트레일·캠핑·쉼터'],
      activities: ['액티비티', '목적지에서 예약할 수 있는 투어'],
      events: ['행사', '축제와 대회'],
    },
  },
  'zh-CN': {
    cta: '免费下载应用',
    note: '安装免费，也不需要应用商店账号。',
    lead: '装好之后离线也能用：地点、路线和急救电话都留在手机里。',
    scan: '扫码在手机上打开',
    dismiss: '关闭',
    alt: 'LaplandVibes 应用界面',
    title: {
      general: '到了|拉普兰？|要用的|信息|都在|手机里。',
      snowmobile: '骑雪地摩托|进山？|把路线|带上。',
      ski: '去拉普兰|滑雪？|雪场和|天气|都在|手机里。',
      stay: '入住|之后，|周边|信息|都在|手机里。',
      move: '在拉普兰|出行？|路况和|道路救援|都在|手机里。',
      outdoors: '走进|大自然？|步道|都在|手机里。',
      do: '在拉普兰|玩什么？|行程和|活动|都在|手机里。',
      eat: '刚到|就饿了？|附近的|餐馆|都在|手机里。',
    },
    screens: {
      now: ['当地|实况', '天气、极光概率和风力'],
      near: ['附近', '餐厅、桑拿、商店'],
      weather: ['天气与|路况', '逐小时官方预报'],
      sos: ['紧急|电话', '112等号码一键拨打'],
      routes: ['雪地摩托|路线', '按市镇列出所有标记路线'],
      ski: ['滑雪场', '{resorts}家滑雪场，{slopes}条雪道和{lifts}部缆车'],
      taxi: ['出租车', '各目的地的本地号码'],
      carhelp: ['汽车|求助', '拖车、轮胎和修理厂，由近到远'],
      outdoors: ['户外', '步道、露营、庇护所'],
      activities: ['活动', '可在目的地预订的行程'],
      events: ['节庆|赛事', '即将举行的节庆、赛事与文化活动'],
    },
  },
};

/** laplandvisitin sää-/ajankohtasivujen revontuliyksikkö ja hätäsivun numeroyksikkö (yhden näkymän aiheet). */
export const UNIT_COPY: Record<'aurora' | 'emergency', Record<string, UnitCopy>> = {
  aurora: {
    en: { title: 'Aurora alerts on your phone', lead: 'The app tells you when the aurora becomes active above the destination you picked. At most once a night, only in season from October to March.', features: ['Aurora now: the chance of seeing it in the next hour', 'Kp index and cloud cover for your destination', 'One alert when activity rises, never a flood'], note: 'On iPhone, add the app to your home screen so alerts can arrive.' },
    fi: { title: 'Revontulihälytys puhelimeesi', lead: 'Appi kertoo, kun revontulet aktivoituvat valitsemasi paikkakunnan yllä. Korkeintaan kerran yössä ja vain kaudella loka–maalis.', features: ['Revontulet nyt: todennäköisyys seuraavan tunnin aikana', 'Kp-indeksi ja pilvisyys kohteessasi', 'Yksi hälytys kun aktiivisuus nousee, ei ilmoitustulvaa'], note: 'iPhonella lisää appi kotinäytölle, jotta ilmoitukset toimivat.' },
    sv: { title: 'Norrskensvarning i mobilen', lead: 'Appen säger till när norrskenet blir aktivt över den ort du valt. Högst en gång per natt och bara under säsongen oktober–mars.', features: ['Norrsken nu: chansen under nästa timme', 'Kp-index och molnighet på din ort', 'En varning när aktiviteten stiger, ingen flod'], note: 'På iPhone: lägg appen på hemskärmen så att varningarna kommer fram.' },
    de: { title: 'Polarlicht-Alarm aufs Handy', lead: 'Die App meldet sich, wenn das Polarlicht über Ihrem gewählten Ort aktiv wird. Höchstens einmal pro Nacht, nur in der Saison von Oktober bis März.', features: ['Polarlicht jetzt: die Chance in der nächsten Stunde', 'Kp-Index und Bewölkung für Ihren Ort', 'Ein Alarm, wenn die Aktivität steigt, keine Flut'], note: 'Auf dem iPhone die App zum Home-Bildschirm hinzufügen, damit Meldungen ankommen.' },
    fr: { title: 'Alerte aurores sur votre téléphone', lead: 'L\'app vous prévient quand l\'aurore s\'active au-dessus de la destination choisie. Au plus une fois par nuit, seulement en saison, d\'octobre à mars.', features: ['Aurores maintenant : la probabilité dans l\'heure', 'Indice Kp et couverture nuageuse à destination', 'Une alerte quand l\'activité monte, pas une avalanche'], note: 'Sur iPhone, ajoutez l\'app à l\'écran d\'accueil pour recevoir les alertes.' },
    es: { title: 'Alertas de auroras en su móvil', lead: 'La app le avisa cuando la aurora se activa sobre el destino que eligió. Como máximo una vez por noche y solo en temporada, de octubre a marzo.', features: ['Aurora ahora: la probabilidad en la próxima hora', 'Índice Kp y nubosidad en su destino', 'Un aviso cuando sube la actividad, sin avalanchas'], note: 'En iPhone, añada la app a la pantalla de inicio para recibir avisos.' },
    it: { title: 'Avviso aurore sul telefono', lead: 'L\'app La avvisa quando l\'aurora si attiva sopra la destinazione scelta. Al massimo una volta per notte e solo in stagione, da ottobre a marzo.', features: ['Aurora adesso: la probabilità nella prossima ora', 'Indice Kp e nuvolosità nella Sua destinazione', 'Un avviso quando l\'attività sale, senza valanghe'], note: 'Su iPhone aggiunga l\'app alla schermata Home per ricevere gli avvisi.' },
    nl: { title: 'Noorderlichtmelding op uw telefoon', lead: 'De app waarschuwt als het noorderlicht actief wordt boven de bestemming die u koos. Hooguit één keer per nacht en alleen in het seizoen, oktober tot maart.', features: ['Noorderlicht nu: de kans in het komende uur', 'Kp-index en bewolking op uw bestemming', 'Eén melding als de activiteit stijgt, geen stortvloed'], note: 'Op iPhone: zet de app op het beginscherm, anders komen meldingen niet aan.' },
    'pt-BR': { title: 'Alerta de aurora no seu celular', lead: 'O app avisa quando a aurora fica ativa sobre o destino que você escolheu. No máximo uma vez por noite e só na temporada, de outubro a março.', features: ['Aurora agora: a chance na próxima hora', 'Índice Kp e nebulosidade no seu destino', 'Um alerta quando a atividade sobe, sem enxurrada'], note: 'No iPhone, adicione o app à tela inicial para receber os alertas.' },
    ja: { title: 'オーロラ通知をスマホに', lead: '選んだ町の上空でオーロラが活発になると、アプリが知らせます。通知は一晩に最大1回、10月〜3月のシーズン中のみ。', features: ['今のオーロラ：次の1時間に見える確率', '滞在先のKp指数と雲量', '活動が高まったときに1回だけ通知'], note: 'iPhoneではアプリをホーム画面に追加すると通知が届きます。' },
    ko: { title: '오로라 알림을 휴대폰으로', lead: '선택한 여행지 상공에서 오로라가 활발해지면 앱이 알려 드립니다. 하룻밤에 최대 한 번, 10월부터 3월까지의 시즌에만.', features: ['지금 오로라: 앞으로 한 시간 안에 볼 확률', '여행지의 Kp 지수와 구름량', '활동이 높아질 때 한 번만 알림'], note: 'iPhone에서는 앱을 홈 화면에 추가해야 알림이 옵니다.' },
    'zh-CN': { title: '极光提醒推送到手机', lead: '当你所选目的地上空的极光活跃起来，应用会通知你。每晚最多一次，仅在 10 月至 3 月的季节内。', features: ['此刻极光：未来一小时看到的概率', '目的地的 Kp 指数和云量', '活动升高时只提醒一次，不刷屏'], note: 'iPhone 用户请将应用添加到主屏幕，通知才能送达。' },
  },
  emergency: {
    en: { title: 'Every emergency number as one call button', lead: 'The LaplandVibes app keeps 112 and Finland\'s other helplines as tap-to-call buttons. Once installed, they stay on your phone even without a network.', features: ['112 first and large, then the 116 117 medical helpline and the Poison Information Centre', 'Road user line, Finavia lost and found and Finnair customer service', 'Numbers checked against Finnish authorities and service providers'], note: 'In an emergency, always call 112 first.' },
    fi: { title: 'Kaikki hätänumerot yhtenä soittonappina', lead: 'LaplandVibes-appi pitää 112:n ja Suomen muut päivystysnumerot soittonappeina. Asennettuna ne ovat tallessa puhelimessa myös ilman verkkoa.', features: ['112 ensin ja isolla, sen alla Päivystysapu 116 117 ja Myrkytystietokeskus', 'Tienkäyttäjän linja, Finavian löytötavarat ja Finnairin asiakaspalvelu', 'Numerot on tarkistettu suomalaisilta viranomaisilta ja palveluntarjoajilta'], note: 'Hätätilanteessa soita aina ensin 112.' },
    sv: { title: 'Alla nödnummer som en ringknapp', lead: 'LaplandVibes-appen har 112 och Finlands övriga hjälpnummer som ringknappar. När den är installerad finns de kvar i mobilen även utan nät.', features: ['112 först och stort, under det Jourhjälpen 116 117 och Giftinformationscentralen', 'Vägtrafikantlinjen, Finavias hittegods och Finnairs kundtjänst', 'Numren är kontrollerade mot finska myndigheter och tjänsteleverantörer'], note: 'I en nödsituation, ring alltid 112 först.' },
    de: { title: 'Alle Notrufnummern als ein Anruf-Button', lead: 'Die LaplandVibes-App hält die 112 und Finnlands weitere Hilfsnummern als Anruf-Buttons bereit. Einmal installiert, bleiben sie auch ohne Netz auf dem Handy.', features: ['112 zuerst und groß, darunter die medizinische Hotline 116 117 und die Giftnotrufzentrale', 'Straßenzustands-Hotline, Finavia-Fundbüro und Finnair-Kundenservice', 'Nummern gegen finnische Behörden und Anbieter geprüft'], note: 'Im Notfall immer zuerst die 112 anrufen.' },
    fr: { title: 'Tous les numéros d\'urgence en un seul bouton', lead: 'L\'app LaplandVibes garde le 112 et les autres lignes d\'aide finlandaises sous forme de boutons d\'appel. Une fois installée, ils restent sur votre téléphone même sans réseau.', features: ['Le 112 d\'abord et en grand, puis la ligne médicale 116 117 et le centre antipoison', 'Ligne info-route, objets trouvés Finavia et service client Finnair', 'Numéros vérifiés auprès des autorités et prestataires finlandais'], note: 'En cas d\'urgence, appelez toujours le 112 en premier.' },
    es: { title: 'Todos los números de emergencia en un solo botón', lead: 'La app LaplandVibes guarda el 112 y los demás teléfonos de ayuda de Finlandia como botones de llamada. Una vez instalada, siguen en su móvil incluso sin red.', features: ['El 112 primero y en grande, debajo la línea médica 116 117 y el Centro de Información Toxicológica', 'Línea del estado de las carreteras, objetos perdidos de Finavia y atención al cliente de Finnair', 'Números comprobados con las autoridades y los proveedores finlandeses'], note: 'En una emergencia, llame siempre primero al 112.' },
    it: { title: 'Tutti i numeri di emergenza in un solo tasto', lead: 'L\'app LaplandVibes tiene il 112 e le altre linee di aiuto finlandesi come tasti di chiamata. Una volta installata, restano sul telefono anche senza rete.', features: ['Il 112 per primo e in grande, sotto la linea medica 116 117 e il Centro antiveleni', 'Linea informazioni stradali, oggetti smarriti Finavia e servizio clienti Finnair', 'Numeri verificati con le autorità e i fornitori finlandesi'], note: 'In un\'emergenza chiami sempre prima il 112.' },
    nl: { title: 'Alle noodnummers als één belknop', lead: 'De LaplandVibes-app bewaart 112 en de andere Finse hulplijnen als belknoppen. Eenmaal geïnstalleerd blijven ze op uw telefoon staan, ook zonder netwerk.', features: ['112 eerst en groot, daaronder de medische hulplijn 116 117 en het Vergiftigingencentrum', 'Wegeninfolijn, gevonden voorwerpen van Finavia en de klantenservice van Finnair', 'Nummers gecontroleerd bij Finse instanties en aanbieders'], note: 'Bel bij een noodgeval altijd eerst 112.' },
    'pt-BR': { title: 'Todos os números de emergência em um só botão', lead: 'O app LaplandVibes guarda o 112 e as outras linhas de ajuda da Finlândia como botões de ligação. Depois de instalado, eles ficam no seu celular mesmo sem rede.', features: ['O 112 primeiro e em destaque, abaixo a linha médica 116 117 e o Centro de Informações Toxicológicas', 'Linha de condições das estradas, achados e perdidos da Finavia e atendimento da Finnair', 'Números conferidos com as autoridades e os prestadores finlandeses'], note: 'Em uma emergência, ligue sempre primeiro para o 112.' },
    ja: { title: '緊急連絡先をワンタップで', lead: 'LaplandVibesアプリは、112とフィンランドのその他の相談窓口をタップで発信できるボタンにまとめています。インストール後は電波がなくてもスマホに残ります。', features: ['最初に大きく112、その下に医療相談116 117と中毒情報センター', '道路情報ライン、Finaviaの遺失物、Finnairカスタマーサービス', '番号はフィンランドの当局と事業者に照合済み'], note: '緊急時はまず必ず112へ。' },
    ko: { title: '모든 긴급 번호를 버튼 하나로', lead: 'LaplandVibes 앱은 112와 핀란드의 다른 도움 전화를 바로 걸기 버튼으로 담고 있습니다. 설치해 두면 네트워크가 없어도 휴대폰에 남아 있습니다.', features: ['112가 맨 위에 크게, 그 아래 의료 상담 116 117과 중독정보센터', '도로 상황 안내, Finavia 분실물 센터, Finnair 고객 서비스', '핀란드 당국과 서비스 제공자에게 확인한 번호'], note: '긴급 상황에서는 항상 112에 먼저 전화하세요.' },
    'zh-CN': { title: '所有紧急号码，一键拨打', lead: 'LaplandVibes 应用把 112 和芬兰其他求助电话做成一键拨打按钮。安装后即使没有网络，它们也留在你的手机里。', features: ['112 排在最前且醒目，其下是医疗咨询 116 117 和中毒信息中心', '路况热线、Finavia 失物招领和芬兰航空客服', '号码已与芬兰当局和服务方核对'], note: '遇到紧急情况，请务必先拨打 112。' },
  },
};
